export const Types = {
  Browse: "Browse",
  Sell: "Sell",
  WishList: "WishList",
  Setting: "Setting",
  ListedItems: "Listed Items",
  Cart: "Cart",
  SearchTerm: "SearchTerm",
  SignIn: "SignIn",
  SignOut: "SignOut",
  Purge: "Purge",
  AuthObject: "AuthObject",
  SignInLocal: "SignInLocal",
  SignOutLocal: "SignOutLocal",
  TiggerErrorMessage: "TiggerErrorMessage",
  WishList: "WishList",
  AddToCart: "AddToCart",
  RemoveFromCart: "RemoveFromCart",
  RemoveAllFromCart: "RemoveAllFromCart",
  IncreaseItemQuantity: "IncreaseItemQuantity",
  DecreaseItemQuantity: "DecreaseItemQuantity",
  PlaceOrder: "PlaceOrder",
  SearchSellTitle: "SearchSellTitle",
  AddtoListed: " AddtoListed",
  RemoveFromListed: "RemoveFromListed",
  FilterPriceUp: "FilterPriceUp",
  FilterPriceDown: "FilterPriceDown",
  FilterAlphaUp: "FilterAlphaUp",
  FilterAlphaDown: "FilterAlphaDown"
};
